import { PAGE_NAMES } from "./pageNames";

export const PAGE = {
  CREATE_GAME: {
    TITLE: PAGE_NAMES.CREATE_GAME,
    GAME_NAME: {
      LABEL: "しあい名",
      NOTE: "（例: 週末じゃんけん）",
      ERROR: "しあい名は50文字以内で入力してください。",
    },
    PLAYER_COUNT: {
      LABEL: "参加人数",
      MIN: 2,
      MAX: 10,
      ERROR: "参加人数を選択してください。",
    },
    NOTICE: "このしあいは作成から1週間有効です。",
    SUBMIT: PAGE_NAMES.CREATE_GAME,
  },
  CREATED_GAME: {
    TITLE: "しあいを作りました",
    GAME_NAME_LABEL: "しあい名",
    GAME_NAME: "週末じゃんけん",
    PLAYER_COUNT_LABEL: "参加人数",
    PLAYER_COUNT: 4,
    EXPIRES_AT_LABEL: "有効期限",
    EXPIRES_AT: "2026年7月12日 23:59まで",
    JOIN_URL_LABEL: "参加URL",
    JOIN_URL: "https://example.com/game/xxxx",
    JOIN_URL_COPY: "参加URLをコピー",
    RESULT_URL_LABEL: "結果URL",
    RESULT_URL: "https://example.com/result/xxxx",
    RESULT_URL_COPY: "結果URLをコピー",
    CREATE_NEW_GAME: PAGE_NAMES.CREATE_GAME,
    COPY_SUCCESS: "コピーしました。",
    COPY_ERROR: "コピーできませんでした。URLを選択してコピーしてください。",
    MODAL_CLOSE: "閉じる",
  },
  PLAY_GAME: {
    TITLE: "週末じゃんけん",
    PARTICIPATION_LABEL: "現在の参加状況",
    PARTICIPATION: "現在 2 / 4 人が参加済みです",
    EXPIRES_AT_LABEL: "有効期限",
    EXPIRES_AT: "2026年7月12日 23:59まで",
    NAME: {
      LABEL: "なまえ",
      DEFAULT_VALUE: "たろう",
      ERROR_REQUIRED: "名前を入力してください。",
      ERROR_MAX_LENGTH: "名前は30文字以内で入力してください。",
    },
    HAND: {
      LABEL: "じゃーんけん",
      ERROR_REQUIRED: "手を選んでください。",
      OPTIONS: [
        {
          value: "rock",
          label: "ぐー",
        },
        {
          value: "scissors",
          label: "ちょき",
        },
        {
          value: "paper",
          label: "ぱー",
        },
      ],
    },
    SUBMIT: "ぽん！",
  },
  WAITING_GAME: {
    TITLE: "送信しました",
    DESCRIPTION: "ほかの参加者を待っています。",
    GAME_NAME_LABEL: "しあい名",
    GAME_NAME: "週末じゃんけん",
    PARTICIPATION_LABEL: "現在の参加人数",
    PARTICIPATION: "2人",
    REQUIRED_PLAYER_COUNT_LABEL: "必要な参加人数",
    REQUIRED_PLAYER_COUNT: "4人",
    PARTICIPATION_SUMMARY: "現在 2 / 4 人が参加済みです",
    EXPIRES_AT_LABEL: "有効期限",
    EXPIRES_AT: "2026年7月12日 23:59まで",
    EXPIRES_AT_SUMMARY: "有効期限: 2026年7月12日 23:59まで",
    RESULT_CHECK: "結果を確認する",
  },
  RESULT_GAME: {
    TITLE: "じゃんけん結果",
    GAME_NAME_LABEL: "しあい名",
    GAME_NAME: "週末じゃんけん",
    RESULT_LABEL: "結果",
    RESULT: "たろうさんの勝ち",
    WINNER_LABEL: "勝者",
    WINNER: "たろうさん",
    PARTICIPANTS_TITLE: "みんなの結果",
    PARTICIPANT_NAME_LABEL: "なまえ",
    PARTICIPANT_HAND_LABEL: "手",
    PARTICIPANT_STATUS_LABEL: "勝敗",
    PARTICIPANTS: [
      {
        name: "たろう",
        hand: "ぐー",
        status: "勝ち",
      },
      {
        name: "はなこ",
        hand: "ちょき",
        status: "負け",
      },
      {
        name: "ゆうた",
        hand: "ちょき",
        status: "負け",
      },
      {
        name: "あおい",
        hand: "ちょき",
        status: "負け",
      },
    ],
    EXPIRES_AT_LABEL: "有効期限",
    EXPIRES_AT: "2026年7月12日 23:59まで",
    EXPIRES_AT_SUMMARY: "有効期限: 2026年7月12日 23:59まで",
    CREATE_NEW_GAME: PAGE_NAMES.CREATE_GAME,
  },
  GAME_EXPIRED: {
    TITLE: "このしあいは期限切れです",
    GAME_NAME_LABEL: "しあい名",
    GAME_NAME: "週末じゃんけん",
    EXPIRES_AT_LABEL: "有効期限",
    EXPIRES_AT: "2026年7月12日 23:59まで",
    DESCRIPTION: "新しいしあいを作って、もう一度遊んでください。",
    CREATE_NEW_GAME: PAGE_NAMES.CREATE_GAME,
  },
} as const;
